### ISSUE TITLE
Guilds Error

### ISSUE THREAD

**Issue by BaiYeLoser** [guilds-plugin/Guilds#119]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Guilds version
* MC Version
* Plugin List
[12:37:00] [Server thread/INFO]: Azitate issued server command: /guild create nmsl
[12:37:09] [Server thread/INFO]: Azitate issued server command: /guilds confirm
[12:37:12] [Craft Scheduler Thread - 3/WARN]: [Guilds] Plugin Guilds v3.4-RELEASE generated an exception while executing task 517
java.lang.IllegalStateException: Not a JSON Object: null
at me.glaremasters.guilds.libs.gson.JsonElement.getAsJsonObject(JsonElement.java:90) ~[?:?]
at me.glaremasters.guilds.guild.GuildSkull.getTextureUrl(GuildSkull.java:62) ~[?:?]
at me.glaremasters.guilds.guild.GuildSkull.<init>(GuildSkull.java:54) ~[?:?]
at me.glaremasters.guilds.commands.management.CommandCreate$1.lambda$accept$0(CommandCreate.java:150) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:personal-8706613]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:personal-8706613]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_181]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_181]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[12:37:15] [Server thread/INFO]: Azitate issued server command: /guild list
[12:37:15] [Server thread/ERROR]: [ACF] Exception in command: guild list
[12:37:15] [Server thread/ERROR]: [ACF] java.lang.reflect.InvocationTargetException
[12:37:15] [Server thread/ERROR]: [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:37:15] [Server thread/ERROR]: [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:37:15] [Server thread/ERROR]: [ACF] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:37:15] [Server thread/ERROR]: [ACF] at java.lang.reflect.Method.invoke(Unknown Source)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:152)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.libs.acf.BaseCommand.executeCommand(BaseCommand.java:576)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.libs.acf.BaseCommand.execute(BaseCommand.java:512)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.libs.acf.RootCommand.execute(RootCommand.java:99)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79)
[12:37:15] [Server thread/ERROR]: [ACF] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[12:37:15] [Server thread/ERROR]: [ACF] at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:700)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1591)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1436)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[12:37:15] [Server thread/ERROR]: [ACF] at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:37:15] [Server thread/ERROR]: [ACF] at java.util.concurrent.FutureTask.run(Unknown Source)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.util.Util.func_181617_a(Util.java:50)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[12:37:15] [Server thread/ERROR]: [ACF] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632)
[12:37:15] [Server thread/ERROR]: [ACF] at java.lang.Thread.run(Unknown Source)
[12:37:15] [Server thread/ERROR]: [ACF] Caused by: java.lang.NullPointerException
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.guild.Guild.getSkull(Guild.java:96)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.guis.ListGUI.setListItem(ListGUI.java:97)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.guis.ListGUI.getListGUI(ListGUI.java:80)
[12:37:15] [Server thread/ERROR]: [ACF] at me.glaremasters.guilds.commands.gui.CommandList.execute(CommandList.java:58)
[12:37:15] [Server thread/ERROR]: [ACF] ... 24 more

When I created the guild, I tried to type /guild list
The console will send the above error, it seems that it is unable to get the head skin caused by...

**Comment by darbyjack** [comment]
Should be fixed!
