### ISSUE TITLE
Cant hit mobs and prefixe dont work

### ISSUE THREAD

**Issue by francisdu30** [guilds-plugin/Guilds#240]
I have instal the plugin from 2 week and no one problem happen but today players cant hit mobs and the prefixe of guild have stop working now they have all {Guilds} in prefixe and not the name of their guilds
When i delete the plugin players can hit mobs again
make damage to mobs*

[Server thread/WARN]:     at me.glaremasters.guilds.guild.GuildHandler.lambda$null$2(GuildHandler.java:167)
[10:29:36] [Server thread/WARN]:     at java.util.ArrayList.forEach(ArrayList.java:1257)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.guild.GuildHandler.lambda$null$3(GuildHandler.java:167)
[10:29:36] [Server thread/WARN]:     at java.util.ArrayList.forEach(ArrayList.java:1257)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.guild.GuildHandler.lambda$new$4(GuildHandler.java:165)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain.nextTask(TaskChain.java:1197)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain.access$1000(TaskChain.java:57)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.next(TaskChain.java:1357)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[10:29:36] [Server thread/WARN]:     at me.glaremasters.guilds.libs.taskchain.TaskChain.lambda$nextTask$19(TaskChain.java:1194)
[10:29:36] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[10:29:36] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Guilds v3.5.3.2-RELEASE
org.bukkit.event.EventException: null
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1613]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.12.2.jar:git-Paper-1613]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1613]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1613]
    at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1393) ~[patched_1.12.2.jar:git-Paper-1613]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1308) ~[patched_1.12.2.jar:git-Paper-1613]
    at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) ~[patched_1.12.2.jar:git-Paper-1613]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
    at java.lang.String.replace(String.java:2240) ~[?:1.8.0_212]
    at me.glaremasters.guilds.listeners.EssentialsChatListener.onPlayerChat(EssentialsChatListener.java:71) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor598.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute

**Comment by francisdu30** [comment]
Work again when i update my paper to the last version
