### ISSUE TITLE
Exception in command: clan promote

### ISSUE THREAD

**Issue by SrBedrock** [guilds-plugin/Guilds#269]
## Description
- Error using `/clan promote` command

```log
>.... [20:53:38 INFO]: InSaNNooo issued server command: /c promote panterang
>.... [20:53:38 ERROR]: [Guilds] [ACF] Exception in command: clan promote panterang
>.... [20:53:38 ERROR]: [Guilds] [ACF] java.lang.reflect.InvocationTargetException
>.... [20:53:38 ERROR]: [Guilds] [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at java.lang.reflect.Method.invoke(Method.java:498)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.libs.acf.RegisteredCommand.invoke(RegisteredCommand.java:153)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.libs.acf.BaseCommand.executeCommand(BaseCommand.java:577)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.libs.acf.BaseCommand.execute(BaseCommand.java:513)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.libs.acf.RootCommand.execute(RootCommand.java:99)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.libs.acf.BukkitRootCommand.execute(BukkitRootCommand.java:79)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1800)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1608)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1088)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at java.lang.Thread.run(Thread.java:748)
>.... [20:53:38 ERROR]: [Guilds] [ACF] Caused by: java.lang.NullPointerException
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.utils.RoleUtils.checkPromote(RoleUtils.java:77)
>.... [20:53:38 ERROR]: [Guilds] [ACF] at me.glaremasters.guilds.commands.member.CommandPromote.execute(CommandPromote.java:88)
>.... [20:53:38 ERROR]: [Guilds] [ACF] ... 26 more
```

## Steps to Reproduce

1. `/clan promote player`

## Environment

**Guilds version**
```log
>....=>.... [15:30:57 INFO]: Guilds version 3.5.3.7-RELEASE
>.... [15:30:57 INFO]: Guilds
>.... [15:30:57 INFO]: Website: https://glaremasters.me/discord
>.... [15:30:57 INFO]: Author: Glare
```

**MC Version**

```log
>....=>.... [15:32:03 INFO]: This server is running Paper version git-Paper-230 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
>.... [15:32:03 INFO]: Checking version, please wait...
>.... [15:32:03 INFO]: Previous version: git-Paper-226 (MC: 1.14.4)
>.... [15:32:03 INFO]: You are running the latest version
```

**Plugin List**

```log
Plugins (50): AuthMe, BackToTheRoots, Bot-Sentry-Spigot, BuycraftX, ChatReaction, ChatReactionPlus, CommandDoesNotExist, CommandPrompter, ConsoleSpamFix, CoreProtect, CrazyCrates, DeluxeCombat, DeluxeCombat_Addon_WG*, DeluxeMenus, DeluxeTags*, EasyChairs, EntityTrackerFixer, Essentials, EssentialsSpawn, FarmLimiter, FastLogin, GetSpawners, GriefPrevention, Guilds, HolographicDisplays, KillerMoney*, LimitPillagers, Lottery, LuckPerms, mcMMO, ModReq*, Multiverse-Core, PlaceholderAPI, PlayerShopGUIPlus, ProtocolLib, PsudoCommand, ShopGUIPlus, SkinsRestorer, SuperbVote, TAB, UltimateChat, Vault, VillagerOptimiser, VKAutoPickup, VoidGenerator, Votifier, Wild, WorldBorder, WorldEdit, WorldGuard
```

**Comment by SrBedrock** [comment]
https://hasteb.in/majawoho.md

**Comment by darbyjack** [comment]
Any chance this occurred after a player was logged out and they changed their username?

**Comment by SrBedrock** [comment]
I don't think so, I'm sure the command was used with the wrong nickname on both occasions.
1. `/c promote panterang` should be `/c promote Panterang`
2. `/clan promote flamengo` should be `/clan promote Flamengo`
