### ISSUE TITLE
Spam console and server freezes

### ISSUE THREAD

**Issue by Seneclor** [guilds-plugin/Guilds#417]
Hello, when a player connects to the server it spam this and the server freezes
* Guilds version : 3.5.5.6
* MC Version : 1.16.5

> [12:59:18] [TaskChainAsyncQueue Thread 14/ERROR]: TaskChain Exception on me.glaremasters.guilds.guild.GuildHandler$$Lambda$6055/456678869: PlayerCommandSendEvent cannot be triggered asynchronously from another thread.
> [12:59:18] [TaskChainAsyncQueue Thread 14/ERROR]: Current Action Index was: 0
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: java.lang.IllegalStateException: PlayerCommandSendEvent cannot be triggered asynchronously from another thread.
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:266)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.updateCommands(CraftPlayer.java:1718)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at org.anjocaido.groupmanager.permissions.BukkitPermissions.updatePermissions(BukkitPermissions.java:233)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at org.anjocaido.groupmanager.permissions.BukkitPermissions.updatePermissions(BukkitPermissions.java:151)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at net.milkbowl.vault.permission.plugins.Permission_GroupManager.playerAdd(Permission_GroupManager.java:132)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at net.milkbowl.vault.permission.Permission.playerAdd(Permission.java:185)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at me.glaremasters.guilds.guild.GuildHandler.lambda$null$16(GuildHandler.java:770)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at java.util.ArrayList.forEach(ArrayList.java:1259)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at me.glaremasters.guilds.guild.GuildHandler.lambda$addPerms$17(GuildHandler.java:768)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at me.glaremasters.guilds.libs.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [12:59:18] [TaskChainAsyncQueue Thread 14/WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by darbyjack** [comment]
This is due to you using GroupManager. You'll probably have to turn the Vault async off in the config because GroupManager is trying to run commands async.

**Comment by Seneclor** [comment]
How does it make to disable the Vault async ?

**Comment by darbyjack** [comment]
There's a config value for this.
