### ISSUE TITLE
Guilds not started

### ISSUE THREAD

**Issue by Anuarr** [guilds-plugin/Guilds#420]
`[14:48:16] [Server thread/INFO]: [Guilds] Enabling Guilds v3.5.5.4

[14:48:16] [Server thread/INFO]:   ________ 
[14:48:16] [Server thread/INFO]:  /  _____/ 
[14:48:16] [Server thread/INFO]: /   \  ___   Guilds v3.5.5.4
[14:48:16] [Server thread/INFO]: \    \_\  \  Server Version: git-Paper-1618 (MC: 1.12.2)
[14:48:16] [Server thread/INFO]:  \______  /
[14:48:16] [Server thread/INFO]:         \/ 
[14:48:16] [Server thread/INFO]: [Guilds] Economy Found: FakeEconomy
[14:48:16] [Server thread/INFO]: [Guilds] Permissions Found: LuckPerms
[14:48:16] [Server thread/ERROR]: Error occurred while enabling Guilds v3.5.5.4 (Is it up to date?)
java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605) ~[zipfs.jar:1.8.0_45]
	at com.sun.nio.zipfs.ZipFileSystem.findEND(ZipFileSystem.java:1021) ~[zipfs.jar:1.8.0_45]
	at com.sun.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1030) ~[zipfs.jar:1.8.0_45]
	at com.sun.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:130) ~[zipfs.jar:1.8.0_45]
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:117) ~[zipfs.jar:1.8.0_45]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:1.8.0_45]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:1.8.0_45]
	at me.glaremasters.guilds.utils.JarFileWalker.walk(JarFileWalker.kt:35) ~[?:?]
	at me.glaremasters.guilds.utils.LanguageUpdater.saveLang(LanguageUpdater.kt:35) ~[?:?]
	at me.glaremasters.guilds.Guilds.onEnable(Guilds.java:180) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
[14:48:16] [Server thread/INFO]: [Guilds] Disabling Guilds v3.5.5.4
[14:48:16] [Server thread/ERROR]: Error occurred while disabling Guilds v3.5.5.4 (Is it up to date?)
java.lang.NullPointerException: null
	at me.glaremasters.guilds.Guilds.onDisable(Guilds.java:102) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
`

**Comment by darbyjack** [comment]
Sounds like the jar is corrupted. Have you tried downloading again and testing?
