### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by SmallFood1026** [guilds-plugin/Guilds#507]
![截圖](https://user-images.githubusercontent.com/75075197/132334515-f760c2a0-4782-4042-9beb-035af1df895d.PNG)

Guilds version: 3.5.6.1
MC Version: 1.17.1

**Comment by darbyjack** [comment]
Can you try compiling the latest commit? This should be fixed. Also delete your `Libraries` folder and let it regen.

**Comment by SmallFood1026** [comment]
[03:14:39 INFO]: [Guilds] Your version of Guilds (3.5.6.1) is up to date!
[03:14:39 WARN]: java.net.UnknownHostException: glaremasters.me
[03:14:39 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
[03:14:39 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
[03:14:39 WARN]:        at java.base/java.net.Socket.connect(Socket.java:645)
[03:14:39 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:300)
[03:14:39 WARN]:        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[03:14:39 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
[03:14:39 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497)
[03:14:39 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:379)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
[03:14:39 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[03:14:39 WARN]:        at Guilds-3.5.6.1_2.jar//me.glaremasters.guilds.utils.StringUtils.getAnnouncements(StringUtils.java:58)
[03:14:39 WARN]:        at Guilds-3.5.6.1_2.jar//me.glaremasters.guilds.Guilds.lambda$onEnable$5(Guilds.java:270)
[03:14:39 WARN]:        at Guilds-3.5.6.1_2.jar//me.glaremasters.guilds.libs.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[03:14:39 WARN]:        at Guilds-3.5.6.1_2.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[03:14:39 WARN]:        at Guilds-3.5.6.1_2.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[03:14:39 WARN]:        at Guilds-3.5.6.1_2.jar//me.glaremasters.guilds.libs.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[03:14:39 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[03:14:39 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[03:14:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[03:14:39 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[03:14:39 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by SmallFood1026** [comment]
I delete Libraries .this is new

**Comment by SmallFood1026** [comment]
It's okay, I solved it, thanks

**Comment by SmallFood1026** [comment]
I solved it Thank you very much the author
