### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by AWGshka** [guilds-plugin/Guilds#522]
## Error log
[org.bukkit.craftbukkit.v1_17_R1.CraftServer] io/github/slimjar/app/builder/ApplicationBuilder initializing Guilds v3.5.6.2-DEV (Is it up to date?)
java.lang.NoClassDefFoundError: io/github/slimjar/app/builder/ApplicationBuilder
	at me.glaremasters.guilds.Guilds.onLoad(Guilds.java:120) ~[Guilds-3.5.6.2-DEV.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.github.slimjar.app.builder.ApplicationBuilder
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Airplane-95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 6 more

later

Error occurred while enabling Guilds v3.5.6.2-DEV (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/platform/bukkit/BukkitAudiences
	at me.glaremasters.guilds.Guilds.onEnable(Guilds.java:187) ~[Guilds-3.5.6.2-DEV.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Airplane-95]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-95]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.platform.bukkit.BukkitAudiences
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Airplane-95]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Airplane-95]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 11 more

## Your Environment
* Guilds version: Guilds-3.5.6.2-DEV
* MC Version: AirPlane 1.17.1
* Plugin List: Plugins (38): AdvancedBan, AdvancedPortals, AdvancedRenamer, AntiRelog, ChatEx*, Citizens, CustomEnderChest, DeluxeMenus, DiscordBotAPI*, FLY, Guilds, HolographicDisplays, IRandomTeleport*, JoinRanks, LuckPerms, Multiverse-Core, MVdWPlaceholderAPI*, ObsidianBreaker*, PL-Hide-Pro, PlaceholderAPI, PlayerKits, PlayerTime*, PleasantWallHack*, ProtectionStones, ProtocolLib, SellGUI, SimpleTpa*, SkinsRestorer, SpawnPlugin*, TAB, UltimateHomes, VanillaEnchants*, Vault, VoidSpawn, Vulcan, WorldEdit, WorldGuard, XConomy

**Comment by AWGshka** [comment]
20 days no answer xd
