### ISSUE TITLE
Crash on starting

### ISSUE THREAD

**Issue by xKsyStudio** [guilds-plugin/Guilds#573]
Bad english, sorry.

## Description
On starting the server, it crashed.
[22:53:15 INFO]: [Guilds] Enabling Guilds v3.5.6.3
[22:53:16 INFO]:   ________
[22:53:16 INFO]:  /  _____/
[22:53:16 INFO]: /   \  ___   Guilds v3.5.6.3
[22:53:16 INFO]: \    \_\  \  Server Version: git-Paper-794 (MC: 1.16.5)
[22:53:16 INFO]:  \______  /
[22:53:16 INFO]:         \/
[22:53:16 ERROR]: Error occurred while enabling Guilds v3.5.6.3 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.Object net.kyori.adventure.platform.facet.FacetAudience.getOrDefault(net.kyori.adventure.pointer.Pointer, java.lang.Object)'
        at net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:100) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:174) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2722) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:174) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        at me.glaremasters.guilds.Guilds.onEnable(Guilds.java:190) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:53:16 INFO]: [Guilds] Disabling Guilds v3.5.6.3

## Expected Behavior
The plugin enabled.

## Actual Behavior
The plugin disabled.

## Possible Fix
I can't give some advice, sorry.

## Steps to Reproduce
1.Just start server with vault

## Context
I have already bought the plugin and can't find aftermarket on discord
If you need to talk more deeply, you can add a discord friend xKsy#7314

## Your Environment
Plugin: Guilds(v3.5.6.3), Vault
Server Version: git-Paper-794 (MC: 1.16.5)
Java: Zulu16

**Comment by darbyjack** [comment]
There is a fix for this provided in the development discord. Would you hop in and try it out?

**Comment by steyn9118** [comment]
@xKsyStudio, have you found a solution to this problem in discord? If so, could you please send me a link?

**Comment by xKsyStudio** [comment]
it has been solved
i forget to close this

**Comment by steyn9118** [comment]
@xKsyStudio how did you solve that?

**Comment by darbyjack** [comment]
This has been fixed in a version releasing soon. You can either compile it or wait for the SpigotMC tree release
