### ISSUE TITLE
Command /guild list doesn't work

### ISSUE THREAD

**Issue by VityaMashina** [guilds-plugin/Guilds#707]
## Description
The command only works if the guild list is empty. When I create a guild, the command stops working.

## Actual Behavior

[13:15:04 INFO]: Nittoi issued server command: /guilds list
[13:15:04 ERROR]: [global] TaskChain Exception on me.glaremasters.guilds.commands.gui.CommandGUI$$Lambda$13520/0x00007fb0e22fb448: Cannot invoke "me.glaremasters.guilds.guild.GuildSkull.getSerialized()" because "this.guildSkull" is null
[13:15:04 ERROR]: [global] Current Action Index was: 0
[13:15:04 WARN]: java.lang.NullPointerException: Cannot invoke "me.glaremasters.guilds.guild.GuildSkull.getSerialized()" because "this.guildSkull" is null
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guild.Guild.getSkull(Guild.java:201)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guis.ListGUI.setListItem(ListGUI.kt:103)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guis.ListGUI.createListItems(ListGUI.kt:90)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guis.ListGUI.get(ListGUI.kt:53)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.commands.gui.CommandGUI.list$lambda$0(CommandGUI.kt:73)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[13:15:04 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[13:15:04 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[13:15:04 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[13:15:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:15:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:15:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)

## Steps to Reproduce

1./g create {guild's name}
2./g list 

## Context

When a player uses a command, the console displays an error. The player doesn't receive an error. The command doesn't work.

## Your Environment

* Guilds version 3.5.7.0
* MC Version 1.20.2
* Plugin List  - AdvancedEnchantments, AntiPopup, antiRedstoneClock, AuctionHouse, BountyHunters, CataMines, Chunky, CMI, CMILib, CrazyCrates, DeluxeMenus, DonatorJoinPlus, EvenMoreFish, FancyNpcs, FastAsyncWorldEdit, GrimAC, Guilds, HeadDatabase, ItemJoin, Jobs, LagAssist, LibsDisguises, LootChest, LuckPerms, Marriage, Multiverse-Core, Multiverse-Inventories, PlaceholderAPI, PlayerParticles, ProtocolLib, SkinsRestorer, SuggestionBlocker, TAB, Vault, Vehicles, ViaVersion, WGExtender, WorldBorder, WorldGuard

**Comment by darbyjack** [comment]
I was not able to reproduce this issue utilize the steps provided:

<img width="465" alt="image" src="https://github.com/guilds-plugin/Guilds/assets/21014720/b6b0eed3-6b7e-4794-9bdf-7e80585dfdd8">

Is there any other information you could provide? Please ensure you are an online-mode server.

**Comment by RICE0707** [comment]
> 我無法使用提供的步驟重現此問題：
> 
> <img alt="影像" width="465" src="https://private-user-images.githubusercontent.com/21014720/297192927-b6b0eed3-6b7e-4794-9bdf-7e80585dfdd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTYwNjMsIm5iZiI6MTcwODMxNTc2MywicGF0aCI6Ii8yMTAxNDcyMC8yOTcxOTI5MjctYjZiMGVlZDMtNmI3ZS00Nzk0LTliZGYtN2U4MDU4NWRmZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMDQzOTA1NjA1ZGI2NDFmNjc4NDI0OTc1MDdmMzMzYjlmMTNmZmUzN2E4YWQ2ZTAwMmUyMTVlM2Q2ZTc0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lHToKbHa7-J3IQ4JZVkgyUhjVQHespiOCwZ_0peCRBE">
> 插件： <img alt="影像" width="473" src="https://private-user-images.githubusercontent.com/21014720/297193142-4da2fbc9-1bff-49ff-a993-29fa4a5be36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTYwNjMsIm5iZiI6MTcwODMxNTc2MywicGF0aCI6Ii8yMTAxNDcyMC8yOTcxOTMxNDItNGRhMmZiYzktMWJmZi00OWZmLWE5OTMtMjlmYTRhNWJlMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYmQ0MmI3NGZkZDYwMTAwODBiZDUwMDNiMTIxMWI4YmIzZmVkOGE0ZmE4ZGY4Yjc3ODcwMjg3OWZmNzdlNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tAxGTKx8ozRrifSJKiw8iknhps8Sj14c3r3z5UeZlsk">
> 
> 您還可以提供其他資訊嗎？請確保您是在線模式伺服器。



> I was not able to reproduce this issue utilize the steps provided:
> 
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/21014720/297192927-b6b0eed3-6b7e-4794-9bdf-7e80585dfdd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTYxNzEsIm5iZiI6MTcwODMxNTg3MSwicGF0aCI6Ii8yMTAxNDcyMC8yOTcxOTI5MjctYjZiMGVlZDMtNmI3ZS00Nzk0LTliZGYtN2U4MDU4NWRmZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkM2Q5YzhmNjIzNTNjMjRkOWM3ZDJmODczZWJjZjI2MjI1MWQ4ZGEwMWU5OWQxM2UyZjIxZjVjODUyZmIzYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwxzdq5jkdZ-uQmY8_NCA5C8sdwGJexM9FSLp5InPKY">
> Plugins: <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/21014720/297193142-4da2fbc9-1bff-49ff-a993-29fa4a5be36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTYxNzEsIm5iZiI6MTcwODMxNTg3MSwicGF0aCI6Ii8yMTAxNDcyMC8yOTcxOTMxNDItNGRhMmZiYzktMWJmZi00OWZmLWE5OTMtMjlmYTRhNWJlMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA0MTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjllNDk5MGQxODE4MzM3NzU1MTlhNzhhZTVmYjQ1OTZkMzA5OTBmODZiNTk0ZDI2YWU2YWNiYjYxMTMyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wn650tg2VAuLvTN7z3u4qrlaKftJQFRoF6g6whjgeIY">
> 
> Is there any other information you could provide? Please ensure you are an online-mode server.

After more complete functional testing, I found that on purpur 1.20.2, the establishment of the guild will lack this data:
```json
  },
  "guildSkull": {
    "serialized": ""
  },
```
In paper 1.20.1, there is no such data error

I used the latest version released by Paper in version 1.20.2, and I also had this error.
This error also exists in versions 1.20.2 and above.

**Comment by RICE0707** [comment]
Moreover, this error will be triggered when the player establishes a guild.
Guilds-3.5.7.0
```
[16:59:46 INFO]: RiceChen_ issued server command: /gd create 測試 t
[16:59:49 INFO]: RiceChen_ issued server command: /gd confirm
[16:59:49 ERROR]: [global] TaskChain Exception on me.glaremasters.guilds.guild.Guild$$Lambda$15400/0x00007fd4feb48440: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
[16:59:49 ERROR]: [global] Current Action Index was: 0
[16:59:49 WARN]: java.lang.Exception: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain.handleError(TaskChain.java:1203)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain.access$600(TaskChain.java:57)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1320)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187)
[16:59:49 WARN]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[16:59:49 WARN]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[16:59:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[16:59:49 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[16:59:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[16:59:49 WARN]: Caused by: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guild.GuildSkull.getTextureUrl(GuildSkull.java:79)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guild.GuildSkull.<init>(GuildSkull.java:52)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.guild.Guild.lambda$updateGuildSkull$10(Guild.java:600)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83)
[16:59:49 WARN]:        at Guilds-3.5.7.0.jar//me.glaremasters.guilds.libs.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312)
[16:59:49 WARN]:        ... 7 more
```

**Comment by hoangxuanlam2007** [comment]
> I was not able to reproduce this issue utilize the steps provided:
> 
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/21014720/297192927-b6b0eed3-6b7e-4794-9bdf-7e80585dfdd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTUxNjYsIm5iZiI6MTcyMTkxNDg2NiwicGF0aCI6Ii8yMTAxNDcyMC8yOTcxOTI5MjctYjZiMGVlZDMtNmI3ZS00Nzk0LTliZGYtN2U4MDU4NWRmZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEzNDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5YTVlYzNjZTViY2Y4MTVjM2VmYTJhMTZiZGE0NzY4MDUyODBhOGIzNWM4OTE0NGMyZmIzYmNmMDcyYjI1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ByjwM1JcmAeAMEdEdArTlZwydp1BaNYAAh2cNFImvCk">
> Plugins: <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/21014720/297193142-4da2fbc9-1bff-49ff-a993-29fa4a5be36e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTUxNjYsIm5iZiI6MTcyMTkxNDg2NiwicGF0aCI6Ii8yMTAxNDcyMC8yOTcxOTMxNDItNGRhMmZiYzktMWJmZi00OWZmLWE5OTMtMjlmYTRhNWJlMzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDEzNDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNTA2ZWQ0ZmZjMmYyMDRkODk1MWZkN2IyZDJkOGRmZGExNTVkMjQzNGVmZDViMWRmMGI4NjFiNjc0NDk0NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QmeX4-D52Qmz7CVycZT1i24rMTlYT-EKiIId7eshh5c">
> 
> Is there any other information you could provide? Please ensure you are an online-mode server.

I'm having the same problem here. And yes, in my server online-mode is set to false due to many crack players even though I've bought Minecraft.
